version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'coshmex_user'
      MYSQL_PASSWORD: 'S3cretoDe#stado##'
      MYSQL_ROOT_PASSWORD: 'S3cretoDe#stado##'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
